# The documentation is at http://goreleaser.com
# Release instructions
# 1) git tag -a 0.1.0-beta.1 -m "Release 0.1.0-beta-1"
# 2) goreleaser          //--skip-publish for dry-run
before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/ts-dump/
  id: ts-dump
  binary: ts-dump
- env:
  - CGO_ENABLED=0
  main: ./cmd/ts-restore/
  id: ts-restore
  binary: ts-restore

#don't publish scoop but overwrite the weird names
scoop:
  name: timescale-backup
  commit_author:
    name: Timescale
    email: support@timescale.com

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
